linters:
  enable-all: true
  disable:
  - exhaustivestruct
  - golint
  - interfacer
  - maligned
  - scopelint
  - gci # conflict goimports
linters-settings:
  goimports:
    local-prefixes: github.com/byakheee/my-discord-bot
